name: live_stocks_tracker
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python>=3.11,<3.13
  - pip
  - libblas=*=*openblas
  - altair
  - lxml
  - numpy
  - pandas
  - pillow
  - pyarrow
  - pytest
  - streamlit
  - pip:
    - anyio==4.10.0
    - beautifulsoup4==4.13.4
    - curl-cffi==0.13.0
    - frozendict==2.4.6
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - httpx-oauth==0.15.1
    - multitasking==0.0.12
    - peewee==3.18.2
    - platformdirs==4.3.8
    - protobuf==6.32.0
    - python-dotenv==1.0.1
    - requests==2.32.5
    - sniffio==1.3.1
    - soupsieve==2.7
    - streamlit-oauth==0.1.14
    - websockets==15.0.1
    - yfinance==0.2.65
