name: live_stocks_tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.13
  - pip
  - libblas=*=*openblas
  - altair
  - lxml
  - numpy
  - pandas
  - pillow
  - pyarrow
  - pytest
  - streamlit
  - pip:
    - annotated-types==0.7.0
    - anyio==4.10.0
    - appdirs==1.4.4
    - beautifulsoup4==4.13.4
    - boltons==25.0.0
    - build==1.3.0
    - cachecontrol==0.14.3
    - click-default-group==1.2.4
    - conda-lock==3.0.4
    - crashtest==0.4.1
    - curl-cffi==0.13.0
    - distlib==0.4.0
    - dulwich==0.22.8
    - ensureconda==1.4.7
    - fastjsonschema==2.21.2
    - filelock==3.19.1
    - frozendict==2.4.6
    - greenlet==3.2.4
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - httpx-oauth==0.15.1
    - installer==0.7.0
    - jaraco-classes==3.4.0
    - jaraco-context==6.0.1
    - jaraco-functools==4.3.0
    - keyring==25.6.0
    - more-itertools==10.7.0
    - msgpack==1.1.1
    - multitasking==0.0.12
    - mysql-connector-python==9.4.0
    - mysqlclient==2.2.7
    - peewee==3.18.2
    - pkginfo==1.12.1.2
    - platformdirs==4.3.8
    - protobuf==6.32.0
    - psycopg2-binary==2.9.11
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - pyproject-hooks==1.2.0
    - python-dotenv==1.0.1
    - pywin32-ctypes==0.2.3 ; platform_system == "Windows"
    - requests==2.32.5
    - requests-toolbelt==1.0.0
    - ruamel-yaml==0.18.15
    - ruamel-yaml-clib==0.2.12
    - semver==3.0.4
    - setuptools==80.9.0
    - shellingham==1.5.4
    - sniffio==1.3.1
    - soupsieve==2.7
    - sqlalchemy==2.0.43
    - sqlite-fts4==1.0.3
    - sqlite-utils==3.38
    - streamlit-oauth==0.1.14
    - tabulate==0.9.0
    - tomlkit==0.13.3
    - trove-classifiers==2025.8.6.13
    - typing-inspection==0.4.1
    - virtualenv==20.34.0
    - websockets==15.0.1
    - yfinance==0.2.65
