name: live_stocks_tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - altair=5.5.0
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.4
  - aws-c-io=0.21.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.33.1
  - aws-sdk-cpp=1.11.606
  - blinker=1.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cachetools=6.1.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - click=8.2.1
  - colorama=0.4.6
  - exceptiongroup=1.3.0
  - gitdb=4.0.12
  - gitpython=3.1.45
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - iniconfig=2.1.0
  - jinja2=3.1.6
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.4.1
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libdeflate=1.24
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.1
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libparquet=21.0.0
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libre2-11=2025.07.22
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lxml=6.0.0
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - mkl=2024.2.2
  - narwhals=2.1.2
  - numpy=2.3.2
  - openjpeg=2.5.3
  - openssl=3.5.2
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.1
  - pillow=11.3.0
  - pip=25.2
  - pluggy=1.6.0
  - pthread-stubs=0.4
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pycparser=2.22
  - pydeck=0.9.1
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=8.4.1
  - python=3.13.5
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - re2=2025.07.22
  - referencing=0.36.2
  - rpds-py=0.27.0
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.2
  - streamlit=1.48.1
  - tbb=2021.13.0
  - tenacity=9.1.2
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.5.2
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - watchdog=6.0.0
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - anyio==4.10.0
      - beautifulsoup4==4.13.4
      - curl-cffi==0.13.0
      - frozendict==2.4.6
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-oauth==0.15.1
      - multitasking==0.0.12
      - peewee==3.18.2
      - platformdirs==4.3.8
      - protobuf==6.32.0
      - python-dotenv==1.0.1
      - requests==2.32.5
      - sniffio==1.3.1
      - soupsieve==2.7
      - streamlit-oauth==0.1.14
      - websockets==15.0.1
      - yfinance==0.2.65

