# .streamlit/secrets.toml
# to change anything go to your google cloud console and fill out the fields below!
[google_oauth]
client_id     = ""
client_secret = ""
redirect_uri       = ""
scope              = ""

# OAuth-endpoint URLs for Google
authorize_url      = ""
token_url          = ""
refresh_token_url  = ""   # Google re-uses token endpoint
revoke_token_url   = ""