name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          if [ -f environment.yml ]; then
            conda env create -f environment.yml || conda env update -f environment.yml
            conda activate $(head -1 environment.yml | cut -d' ' -f2)  # assumes 'name: myenv' is first line
          fi

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
